export const starterPokemon = [
    "bulbasaur",
    "ivysaur",
    "charmander",
    "charmeleon",
    "squirtle",
    "wartortle",
  
    "chikorita",
    "bayleef",
    "cyndaquil",
    "quilava",
    "totodile",
    "croconaw",
  
    "treecko",
    "grovyle",
    "torchic",
    "combusken",
    "mudkip",
    "marshtomp",
  
    "turtwig",
    "grotle",
    "chimchar",
    "monferno",
    "piplup",
    "prinplup",
  
    "snivy",
    "servine",
    "tepig",
    "pignite",
    "oshawott",
    "dewott",
  
    "chespin",
    "quilladin",
    "fennekin",
    "braixen",
    "froakie",
    "frogadier",
  
    "rowlet",
    "dartrix",
    "litten",
    "torracat",
    "popplio",
    "brionne",
  
    "grookey",
    "thwackey",
    "scorbunny",
    "raboot",
    "sobble",
    "drizzile",
  
    "sprigatito",
    "floragato",
    "fuecoco",
    "crocalor",
    "quaxly",
    "quaxwell"
  ];